import React from 'react';
import { UnifiedPlan } from '../types';
import ItineraryPreview from './ItineraryPreview';
import PackingListPreview from './PackingListPreview';
import FoodFinderResult from './FoodFinderResult';
import AppFinderResult from './AppFinderResult';
import MusicFinderResult from './MusicFinderResult';
import LingoFinderResult from './LingoFinderResult';

interface GuidebookProps {
  plan: UnifiedPlan;
}

const Guidebook: React.FC<GuidebookProps> = ({ plan }) => {
  if (!plan.itinerary) return null; // Itinerary is required for a guidebook

  const destinationName = plan.itinerary.destination;

  return (
    <div id="guidebook-content">
      {/* Cover Page */}
      <div className="guidebook-page cover-page">
        <div className="cover-content">
          <span className="cover-subtitle">Your Personalized Travel Guidebook</span>
          <h1 className="cover-title">{destinationName}</h1>
          <p className="cover-footer">Generated by Planora AI</p>
        </div>
      </div>

      {/* Table of Contents */}
      <div className="guidebook-page toc-page">
        <div className="toc-content">
          <h2 className="toc-title">Table of Contents</h2>
          <nav>
            <ul className="toc-list">
              {plan.itinerary && <li><a href="#gb-itinerary">Full Itinerary</a></li>}
              {plan.packingList && <li><a href="#gb-packing">Packing List</a></li>}
              {plan.foodRecommendations && <li><a href="#gb-food">Food Guide</a></li>}
              {plan.appRecommendations && <li><a href="#gb-apps">Local Apps</a></li>}
              {plan.musicRecommendations && <li><a href="#gb-music">Music Playlist</a></li>}
              {plan.lingoRecommendations && <li><a href="#gb-lingo">Lingo Guide</a></li>}
            </ul>
          </nav>
        </div>
      </div>

      {/* Sections */}
      {plan.itinerary && (
        <div id="gb-itinerary" className="guidebook-page">
          <ItineraryPreview itinerary={plan.itinerary} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
      {plan.packingList && (
        <div id="gb-packing" className="guidebook-page">
          <PackingListPreview packingList={plan.packingList} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
      {plan.foodRecommendations && (
        <div id="gb-food" className="guidebook-page">
          <FoodFinderResult recommendations={plan.foodRecommendations} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
      {plan.appRecommendations && (
        <div id="gb-apps" className="guidebook-page">
          <AppFinderResult recommendations={plan.appRecommendations} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
      {plan.musicRecommendations && (
        <div id="gb-music" className="guidebook-page">
          <MusicFinderResult recommendations={plan.musicRecommendations} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
      {plan.lingoRecommendations && (
        <div id="gb-lingo" className="guidebook-page">
            <LingoFinderResult recommendations={plan.lingoRecommendations} onRegenerate={() => {}} isUnifiedView />
        </div>
      )}
    </div>
  );
};

export default Guidebook;
